// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8EpmfJekWA4uF5712JsjtiyybZxetZd4',
    appId: '1:1007174949215:web:4b129124186f6e3f90feea',
    messagingSenderId: '1007174949215',
    projectId: 'rtoda-notification-syste-255ce',
    authDomain: 'rtoda-notification-syste-255ce.firebaseapp.com',
    storageBucket: 'rtoda-notification-syste-255ce.firebasestorage.app',
    measurementId: 'G-P5BSNCVTZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDloPBQvcjprutbUva6-HizIlB2k1T1T3U',
    appId: '1:1007174949215:android:f700e4d6b3cef0d790feea',
    messagingSenderId: '1007174949215',
    projectId: 'rtoda-notification-syste-255ce',
    storageBucket: 'rtoda-notification-syste-255ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK9xqB39eNymkCC1jhbNkGZ2CrxWAw8aY',
    appId: '1:1007174949215:ios:c01b83b5ec88292990feea',
    messagingSenderId: '1007174949215',
    projectId: 'rtoda-notification-syste-255ce',
    storageBucket: 'rtoda-notification-syste-255ce.firebasestorage.app',
    iosBundleId: 'com.example.reportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK9xqB39eNymkCC1jhbNkGZ2CrxWAw8aY',
    appId: '1:1007174949215:ios:c01b83b5ec88292990feea',
    messagingSenderId: '1007174949215',
    projectId: 'rtoda-notification-syste-255ce',
    storageBucket: 'rtoda-notification-syste-255ce.firebasestorage.app',
    iosBundleId: 'com.example.reportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8EpmfJekWA4uF5712JsjtiyybZxetZd4',
    appId: '1:1007174949215:web:13d64b5f0174cc3c90feea',
    messagingSenderId: '1007174949215',
    projectId: 'rtoda-notification-syste-255ce',
    authDomain: 'rtoda-notification-syste-255ce.firebaseapp.com',
    storageBucket: 'rtoda-notification-syste-255ce.firebasestorage.app',
    measurementId: 'G-NY0JNLEQ56',
  );
}
